version: '2'
services:
    eudorahack-app:
        image: eudorahack
        external_links:
            - eudorahack-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/eudorahack
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    eudorahack-postgresql:
        extends:
            file: postgresql.yml
            service: eudorahack-postgresql
